package com.study.mybatis.dmo;

import java.util.List;

public class ClazzDmo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.id
     *
     * @mbg.generated Mon Jul 03 19:40:52 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.name
     *
     * @mbg.generated Mon Jul 03 19:40:52 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Jul 03 19:40:52 CST 2017
     */
    public ClazzDmo(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Jul 03 19:40:52 CST 2017
     */
    public ClazzDmo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.id
     *
     * @return the value of clazz.id
     *
     * @mbg.generated Mon Jul 03 19:40:52 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.id
     *
     * @param id the value for clazz.id
     *
     * @mbg.generated Mon Jul 03 19:40:52 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.name
     *
     * @return the value of clazz.name
     *
     * @mbg.generated Mon Jul 03 19:40:52 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.name
     *
     * @param name the value for clazz.name
     *
     * @mbg.generated Mon Jul 03 19:40:52 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
    
    private List<StudentDmo> students;

	public List<StudentDmo> getStudents() {
		return students;
	}

	public void setStudents(List<StudentDmo> students) {
		this.students = students;
	}

	@Override
	public String toString() {
		return "ClazzDmo [id=" + id + ", name=" + name + "]";
	}
    
    
}