package com.study.mybatis.dmo;

import java.util.Date;

public class StudentDmo {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column student.id
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	private Long id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column student.name
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column student.age
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	private Integer age;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column student.gender
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	private Boolean gender;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column student.birthday
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	private Date birthday;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column student.clazz
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	private ClazzDmo clazz;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	public StudentDmo(Long id, String name, Integer age, Boolean gender, Date birthday, ClazzDmo clazz) {
		this.id = id;
		this.name = name;
		this.age = age;
		this.gender = gender;
		this.birthday = birthday;
		this.clazz = clazz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	public StudentDmo() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column student.id
	 *
	 * @return the value of student.id
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column student.id
	 *
	 * @param id
	 *            the value for student.id
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column student.name
	 *
	 * @return the value of student.name
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column student.name
	 *
	 * @param name
	 *            the value for student.name
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column student.age
	 *
	 * @return the value of student.age
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column student.age
	 *
	 * @param age
	 *            the value for student.age
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column student.gender
	 *
	 * @return the value of student.gender
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	public Boolean getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column student.gender
	 *
	 * @param gender
	 *            the value for student.gender
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column student.birthday
	 *
	 * @return the value of student.birthday
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column student.birthday
	 *
	 * @param birthday
	 *            the value for student.birthday
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column student.clazz
	 *
	 * @return the value of student.clazz
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	public ClazzDmo getClazz() {
		return clazz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column student.clazz
	 *
	 * @param clazz
	 *            the value for student.clazz
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	public void setClazz(ClazzDmo clazz) {
		this.clazz = clazz;
	}

	@Override
	public String toString() {
		return "StudentDmo [id=" + id + ", name=" + name + ", age=" + age + ", gender=" + gender + ", birthday="
				+ birthday + ", clazz.id=" + clazz.getId() + ",clazz.name=" + clazz.getName() + "]";
	}

}