package com.study.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.study.mybatis.dmo.StudentDmo;

public interface StudentDao {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	List<StudentDmo> selectStudentsByNameAndClazz_IdIn(@Param("name") String name,
			@Param("clazzIds") List<Long> clazzIds);

	List<StudentDmo> selectStudentByClazz_Id(Long cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	int insert(StudentDmo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	StudentDmo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	List<StudentDmo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbg.generated Mon Jul 03 19:40:52 CST 2017
	 */
	int updateByPrimaryKey(StudentDmo record);
}