package com.study.mybatis.dao;

import com.study.mybatis.dmo.StudentDmo;
import java.util.List;

public interface StudentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Jul 03 19:40:52 CST 2017
     */
    int deleteByPrimaryKey(Long id);
    
    List<StudentDmo> selectStudentByClazz_Id(Long cid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Jul 03 19:40:52 CST 2017
     */
    int insert(StudentDmo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Jul 03 19:40:52 CST 2017
     */
    StudentDmo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Jul 03 19:40:52 CST 2017
     */
    List<StudentDmo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Jul 03 19:40:52 CST 2017
     */
    int updateByPrimaryKey(StudentDmo record);
}