package com.study.mybatis.mapper;

import com.study.mybatis.dmo.RoleDmo;
import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 01 20:39:02 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 01 20:39:02 CST 2017
     */
    int insert(RoleDmo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 01 20:39:02 CST 2017
     */
    RoleDmo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 01 20:39:02 CST 2017
     */
    List<RoleDmo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 01 20:39:02 CST 2017
     */
    int updateByPrimaryKey(RoleDmo record);
}