package com.study.mybatis.mapper;

import com.study.mybatis.dmo.UserDmo;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 01 20:37:50 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 01 20:37:50 CST 2017
     */
    int insert(UserDmo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 01 20:37:50 CST 2017
     */
    UserDmo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 01 20:37:50 CST 2017
     */
    List<UserDmo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 01 20:37:50 CST 2017
     */
    int updateByPrimaryKey(UserDmo record);
}