package com.study.mybatis.mapper;

import com.study.mybatis.dmo.UserDmo;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 01 20:15:56 CST 2017
     */
    @Delete({
        "delete from user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 01 20:15:56 CST 2017
     */
    @Insert({
        "insert into user (username, age, ",
        "gender, birthday, balance, ",
        "register_time)",
        "values (#{username,jdbcType=VARCHAR}, #{age,jdbcType=INTEGER}, ",
        "#{gender,jdbcType=BIT}, #{birthday,jdbcType=DATE}, #{balance,jdbcType=INTEGER}, ",
        "#{registerTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(UserDmo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 01 20:15:56 CST 2017
     */
    @Select({
        "select",
        "id, username, age, gender, birthday, balance, register_time",
        "from user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.INTEGER),
        @Result(column="gender", property="gender", jdbcType=JdbcType.BIT),
        @Result(column="birthday", property="birthday", jdbcType=JdbcType.DATE),
        @Result(column="balance", property="balance", jdbcType=JdbcType.INTEGER),
        @Result(column="register_time", property="registerTime", jdbcType=JdbcType.TIMESTAMP)
    })
    UserDmo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 01 20:15:56 CST 2017
     */
    @Select({
        "select",
        "id, username, age, gender, birthday, balance, register_time",
        "from user"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.INTEGER),
        @Result(column="gender", property="gender", jdbcType=JdbcType.BIT),
        @Result(column="birthday", property="birthday", jdbcType=JdbcType.DATE),
        @Result(column="balance", property="balance", jdbcType=JdbcType.INTEGER),
        @Result(column="register_time", property="registerTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<UserDmo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 01 20:15:56 CST 2017
     */
    @Update({
        "update user",
        "set username = #{username,jdbcType=VARCHAR},",
          "age = #{age,jdbcType=INTEGER},",
          "gender = #{gender,jdbcType=BIT},",
          "birthday = #{birthday,jdbcType=DATE},",
          "balance = #{balance,jdbcType=INTEGER},",
          "register_time = #{registerTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserDmo record);
}